### PR TITLE
Add Admin Management & API to User Service Component

### PR DESCRIPTION
**Pull request by Kidsnd274**
### Changes Made:
- Created API Endpoints for Admin Management
- Refactored the user service component
- Fixed Dockerfile for User Service
- Added waitress as the WSGI server for User Service
- Added basic docker-compose.yaml file (can just `docker compose up` in the root project directory
- Followed firebase credentials json naming standard to `firebase-cred.json`

### Difference between question_service and user_service
The location to put the `.env` and `firebase-cred.json` is different in both of these services. (Currently)
- For **question_service**: Place it in `backend\question_service\app`
- For **user_service**: Place it in `backend\user_service`

### How to test
Test out the API calls using Bruno. Check the README for the Admin Endpoints

### Additional Notes:
- Updated the method to start the user-service server. Check the README for details.
- API Endpoints for Admin Management are listed in the README

### CODE REVIEW

**Comment by Kidsnd274** [comment]
DO NOT MERGE NOW

**Comment by Kidsnd274** [comment]
Ok can merge already. Just some Docker changes to take note of:

- docker-compose.yaml added, and supports both frontend, question_service and user_service
- The standard naming for the firebase credentials json is `firebase-cred.json`
- Also in the .env, it is sufficient to use `CRED_PATH=./firebase-cred.json` even on a Windows Python install

## Difference between question_service and user_service
The location to put the `.env` and `firebase-cred.json` is different in both of these services.
- For **question_service**: Place it in `backend\question_service\app`
- For **user_service**: Place it in `backend\user_service`

**Comment by Huggenguggen** [comment]
LGTM!
A few small notes,
1. Due to the way you structured the user_service, backend\user_service\app\main.py  is no longer necessary and can be removed in a future PR
2. You might want to consider making the user settings page more fleshed out so that it actually utilizes the user_service in a future PR (admin view/user view)

But otherwise, GJ! 😄

**Review by Huggenguggen — APPROVED** [review]
LGTM

**Comment by Kidsnd274** [comment]
Finishes #8

**Pull request merged**
